'use client';

import React, { useCallback, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { AnimatePresence, motion } from 'framer-motion';

interface DisclaimerModalProps {
  isOpen: boolean;
  onAccept: () => void;
  onDecline: () => void;
}

const DISCLAIMER_ITEMS = [
  {
    code: 'BETA',
    title: 'Under Active Development',
    text: 'SoSo Analyst is in beta. Features may change, break, or become temporarily unavailable without notice.',
  },
  {
    code: 'AI',
    title: 'AI Can Be Wrong',
    text: 'Responses are generated by AI and may contain inaccuracies, hallucinations, or outdated information. Always verify critical data independently.',
  },
  {
    code: 'RISK',
    title: 'Not Financial Advice',
    text: 'Nothing provided by this tool constitutes financial, investment, or trading advice. All analysis is for informational purposes only.',
  },
  {
    code: 'DATA',
    title: 'Data Accuracy',
    text: 'Market data is sourced from third-party APIs and may be delayed, incomplete, or inaccurate. Do not rely on it for trading decisions.',
  },
  {
    code: 'AUTH',
    title: 'Wallet Connection',
    text: 'Connecting your wallet is used for authentication and chat persistence only. We never request token approvals or transaction signatures beyond identity verification.',
  },
];

interface DisclaimerDialogProps {
  onAccept: () => void;
  onDecline: () => void;
}

const DisclaimerDialog: React.FC<DisclaimerDialogProps> = ({ onAccept, onDecline }) => {
  const [acknowledged, setAcknowledged] = useState(false);

  const handleKeyDown = useCallback((event: KeyboardEvent) => {
    if (event.key === 'Escape') onDecline();
  }, [onDecline]);

  useEffect(() => {
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [handleKeyDown]);

  const handleAccept = useCallback(() => {
    if (!acknowledged) return;
    onAccept();
  }, [acknowledged, onAccept]);

  return (
    <motion.div
      key="wallet-disclaimer"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.2 }}
      className="fixed inset-0 z-[100000] flex items-center justify-center p-4"
      onClick={onDecline}
    >
      <div className="absolute inset-0 bg-black/75 backdrop-blur-sm" />

      <motion.div
        role="dialog"
        aria-modal="true"
        aria-labelledby="wallet-disclaimer-title"
        initial={{ opacity: 0, scale: 0.95, y: 12 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 12 }}
        transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }}
        onClick={(event) => event.stopPropagation()}
        className="relative w-full max-w-lg max-h-[85vh] overflow-hidden rounded-lg border border-accent-green/30 bg-[#060A06] shadow-[0_0_60px_rgba(0,255,157,0.08),0_24px_80px_rgba(0,0,0,0.7)]"
      >
        <div className="absolute inset-0 pointer-events-none bg-[linear-gradient(rgba(0,255,157,0.012)_50%,transparent_50%)] bg-[length:100%_4px] opacity-40 rounded-lg z-10" />

        <div className="px-5 pt-5 pb-3 border-b border-border/60">
          <div className="flex items-center gap-2.5">
            <div className="w-2 h-2 bg-accent-amber rounded-full shadow-[0_0_8px_rgba(255,184,0,0.6)] animate-pulse" />
            <h2
              id="wallet-disclaimer-title"
              className="text-sm font-mono font-bold text-accent-green uppercase tracking-[0.15em] text-glow-green"
            >
              System Notice
            </h2>
          </div>
          <p className="mt-2 text-[11px] font-mono text-text-secondary tracking-wide">
            Please review the following before proceeding.
          </p>
        </div>

        <div className="overflow-y-auto max-h-[50vh] px-5 py-4 space-y-3 custom-scrollbar">
          {DISCLAIMER_ITEMS.map((item, index) => (
            <motion.div
              key={item.code}
              initial={{ opacity: 0, x: -8 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.06, duration: 0.2 }}
              className="flex gap-3 p-3 rounded-md border border-border/50 bg-surface/40 hover:border-accent-green/20 transition-colors"
            >
              <span className="mt-0.5 flex h-5 w-11 shrink-0 items-center justify-center rounded-sm border border-accent-green/25 bg-accent-green/[0.06] text-[9px] font-mono font-bold uppercase tracking-wider text-accent-green">
                {item.code}
              </span>
              <div className="min-w-0">
                <div className="text-xs font-mono font-bold text-white uppercase tracking-wider mb-1">
                  {item.title}
                </div>
                <p className="text-[11px] font-sans text-text-secondary leading-relaxed">
                  {item.text}
                </p>
              </div>
            </motion.div>
          ))}
        </div>

        <div className="px-5 py-4 border-t border-border/60 space-y-3">
          <label className="flex items-start gap-2.5 cursor-pointer group select-none">
            <div className="relative mt-0.5 shrink-0">
              <input
                type="checkbox"
                checked={acknowledged}
                onChange={(event) => setAcknowledged(event.target.checked)}
                className="peer sr-only"
              />
              <div className="w-4 h-4 rounded-sm border border-border/80 bg-[#0A0F0A] peer-checked:border-accent-green/60 peer-checked:bg-accent-green/15 transition-colors flex items-center justify-center">
                {acknowledged && (
                  <svg className="w-2.5 h-2.5 text-accent-green" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                )}
              </div>
            </div>
            <span className="text-[11px] font-mono text-text-secondary group-hover:text-text-primary transition-colors leading-relaxed">
              I understand that this application is in beta, AI-generated analysis may be inaccurate, and nothing here constitutes financial advice.
            </span>
          </label>

          <div className="flex items-center justify-end gap-2.5">
            <button
              type="button"
              onClick={onDecline}
              className="px-4 py-2 text-[10px] font-mono font-bold uppercase tracking-widest text-text-secondary border border-border/60 rounded-md hover:text-white hover:border-border-bright transition-colors"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleAccept}
              disabled={!acknowledged}
              className="px-5 py-2 text-[10px] font-mono font-bold uppercase tracking-widest rounded-md transition-all disabled:opacity-30 disabled:cursor-not-allowed bg-accent-green text-[#030503] hover:bg-accent-green/90 shadow-[0_0_18px_rgba(0,255,157,0.15)] hover:shadow-[0_0_28px_rgba(0,255,157,0.25)] disabled:shadow-none"
            >
              Accept and Continue
            </button>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
};

const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ isOpen, onAccept, onDecline }) => {
  if (typeof document === 'undefined') return null;

  return createPortal(
    <AnimatePresence>
      {isOpen && (
        <DisclaimerDialog onAccept={onAccept} onDecline={onDecline} />
      )}
    </AnimatePresence>,
    document.body
  );
};

export default DisclaimerModal;
